# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0C0D11"
foreground = "#F7E7C8"

[colors.normal]
black   = "#27282C"
red     = "#5F221D"
green   = "#675F62"
yellow  = "#CA5140"
blue    = "#B09A94"
magenta = "#8C7C7B"
cyan    = "#953A2E"
white   = "#F7E7C8"

[colors.bright]
black   = "#4B4C50"
red     = "#5F221D"
green   = "#675F62"
yellow  = "#CA5140"
blue    = "#B09A94"
magenta = "#8C7C7B"
cyan    = "#953A2E"
white   = "#F7E7C8"
