# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#0F0A07"
foreground = "#F6D3BE"

[colors.normal]
black   = "#2E2623"
red     = "#5F524E"
green   = "#7A5D58"
yellow  = "#6D645D"
blue    = "#8F6960"
magenta = "#8D7971"
cyan    = "#B46F5A"
white   = "#F6D3BE"

[colors.bright]
black   = "#514B48"
red     = "#6C5A55"
green   = "#906862"
yellow  = "#7E7369"
blue    = "#A77164"
magenta = "#99786B"
cyan    = "#F09478"
white   = "#F6D3BE"
