schema_version = "1.0.0"

id = "Bagapie"
version = "11.0.8"
name = "Bagapie"
tagline = "50+ tools : Scattering, Ivy Gen, Random Array, Architecture"
maintainer = "Antoine Bagattini <bagattini.studio@gmail.com>"

type = "add-on"

website = "https://www.f12studio.fr/bagapiev6"

tags=["Modeling","Node"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2019-2025 Antoine Bagattini",
]

[permissions]
network = "Open web browser for documentation and tutorials"
files = "Create, setup and add assets libraries"