set-option -sa terminal-overrides ",xterm*:RGB"
set-option -g default-shell /bin/fish
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

unbind C-b
set -g prefix `
bind ` send-prefix
set -g mouse on
bind r source-file ~/.config/tmux/tmux.conf

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/sensible'
set -g @plugin 'tmux-plugins/resurrect'
set -g @plugin 'tmux-plugins/continuum'
# set -g @plugin '2kabhishek/tmux2k'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

set -g @continuum-restore 'on'
set -g @continuum-boot 'on'

# set -g @tmux2k-theme 'duo'
# set -g @tmux2k-icons-only false
# set -g @tmux2k-bg-main 'default'
# set -g @tmux2k-duo-bg '#111111'
# set -g @tmux2k-duo-fg 'yellow'
# set -g @tmux2k-bandwidth-network-name wlan0
# set -g @tmux2k-right-plugins 'time'

set -g status-position bottom
set -g status-fg white

run '~/.tmux/plugins/tpm/tpm'
