schema_version = "1.0.0"
id = "Quick_Studio_Light"
name = "Quick Studio Light"
version = "1.1.2"
tagline = "Simple and fast lighting with improved selection"
maintainer = "Shuimeng"
type = "add-on"
tags = ["Lighting","3D View"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Shuimeng"]