schema_version = "1.0.0"
id = "parallax_node"
version = "1.1.1"
name = "Parallax Node"
tagline = "Adds parallax node for shader nodes"
maintainer = "crantisz@gmail.com"
type = "add-on"

website = "https://multlabs.com"

tags = ["Material" , "Node"]

blender_version_min = "5.0.0"
license = [
  "SPDX:GPL-3.0-or-later",
]


[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  ".gitignore"
]