$mainMod = SUPER

# plugin {
#   hyprtasking {
#     layout = grid
#
#     gap_size = 25
#     bg_color = 0x111111
#     border_size = 4
#     exit_on_hovered = false
#     warp_on_move_window = 1
#     close_overview_on_reload = true
#
#     drag_button = 0x111 # right mouse button
#     select_button = 0x110 # left mouse button
#     # for other mouse buttons see <linux/input-event-codes.h>
#
#     gestures {
#         enabled = true
#         move_fingers = 3
#         move_distance = 300
#         open_fingers = 4
#         open_distance = 300
#         open_positive = true
#     }
#
#     grid {
#         rows = 2
#         cols = 2
#         loop = false
#         gaps_use_aspect_ratio = true
#     }
#
#     linear {
#         height = 600
#         scroll_speed = 1.0
#         blur = false
#     }
#   }
#   # hyprexpo {
#   #   columns = 2
#   #   gap_size = 5
#   #   bg_col = rgb(111111)
#   #   workspace_method = center m+1 # [center/first] [workspace] e.g. first 1 or center m+1
#   #   skip_empty = true
#   #   gesture_distance = 300 # how far is the "max" for the gesture
#   # }
#   hyprfocus {
#     mode = flash
#     only_on_monitor_change = false
#     fade_opacity = 0.9
#     bounce_strength = 0.99
#     slide_height = 20
#   }
# }

source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/decorations.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/windowrules.conf

