# Blender Extension Manifest
schema_version = "1.0.0"

id = "sidebar_tab_search"
version = "2.0.0"
name = "Sidebar Tab Search"
tagline = "Quick search and switch between Sidebar (N-Panel) tabs"
maintainer = "McKaa"
type = "add-on"

# Minimum Blender version
blender_version_min = "4.2.0"

# License (SPDX format)
license = [
  "SPDX:GPL-3.0-or-later",
]

# Tags (Used for searching on the platform)
tags = ["3D View", "User Interface"]

# Optional: Link to source (Useful, but can be removed if you want total minimalism)
website = "https://github.com/McKaa/sidebar-tab-search-blender-addon"