# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Animations Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/0.45.0/Configuring/Animations/ 

animations {
    enabled = no

    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    bezier = smoothIn, 0.25, 1.0, 0.5, 1.0
    bezier = smoothOut, 0.05, 0.9, 0.1, 1.05
    bezier = softSnap, 0.4, 0, 0.2, 1.0
    bezier = fluent, 0.0, 0.0, 0.2, 1.0

    animation = windows, 1, 3, fluent, slide
    animation = windowsIn, 1, 3, fluent, slide
    animation = windowsOut, 1, 3, fluent, slide
    animation = windowsMove, 1, 3, overshot

    animation = layersIn, 1, 3, smoothIn
    animation = layersOut, 1, 3, smoothOut

    animation = fade, 1, 3, smoothIn
    animation = fadeIn, 1, 3, smoothIn
    animation = fadeOut, 1, 3, smoothOut
    animation = fadeSwitch, 1, 3, smoothIn
    animation = fadeShadow, 1, 3, smoothIn
    animation = fadeDim, 1, 3, smoothIn
    animation = fadeDpms, 1, 3, smoothIn
    animation = fadeLayers, 1, 3, softSnap

    animation = workspaces, 1, 3, softSnap, slidefadevert 50%
    animation = specialWorkspace, 1, 3, fluent, slidefadevert 50%
}
