# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$filemanager = pcmanfm
$applauncher = pkill -x wofi >/dev/null 2>&1 || wofi -i --show drun
$wmenu = pkill -x wmenu-drun >/dev/null 2>&1 || wmenu-drun
# $applauncher = pkill -x fuzzel >/dev/null 2>&1 || fuzzel
# $emojipicker = pkill -x wofi >/dev/null 2>&1 || wofi-emoji
$emojipicker = pkill -x wmenu-emoji >/dev/null 2>&1 || wmenu-emoji
$wallswitcher = pkill -x waypaper >/dev/null 2>&1 || waypaper
# $wallswitcher = qs -c noctalia-shell ipc call wallpaper toggle
$terminal = kitty
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
# $capturing = grim -g "$(slurp)" - | swappy -f -
# $screencap = grim - | swappy -f -
$capturing = hyprshot -m region -r - | swappy -f -
$screencap = hyprshot -m output -m eDP-1 -r - | swappy -f -
$browser = zen-browser
