# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/#input

input {
    numlock_by_default = true
    follow_mouse = 1 # 0|1|2|3
    float_switch_override_focus = 2
    kb_model = pc102
    kb_layout = us
}

exec-once = setxkbmap -model pc105 -layout us -option grp:shifts_toggle

cursor {
    no_warps = true
}
