$wallpaper = /home/alef/Pictures/walls/wallhaven-p838q3.png
$background = rgb(171717)
$foreground = rgb(BDE3F6)
$color0 = rgb(424242)
$color1 = rgb(4A525B)
$color2 = rgb(4B6571)
$color3 = rgb(486789)
$color4 = rgb(497C97)
$color5 = rgb(468CAF)
$color6 = rgb(3C89B1)
$color7 = rgb(98CFEA)
$color8 = rgb(6A91A4)
$color9 = rgb(4F5A66)
$color10 = rgb(507484)
$color11 = rgb(4D75A4)
$color12 = rgb(448DB2)
$color13 = rgb(168ECB)
$color14 = rgb(42AFE6)
$color15 = rgb(98CFEA)
