-- hyprland.lua
-- Generated by hypr-migrate from: animations.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       0 resolved
--   Config keys:     1 emitted
--   Monitors:        0
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   0
--   Gestures:        0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

hl.config({
  animations = {
    enabled = true,
  },
})

hl.curve("overshot", {
  type = "bezier",
  points = { { 0.05, 0.9 }, { 0.1, 1.05 } }
})
hl.curve("smoothIn", {
  type = "bezier",
  points = { { 0.25, 1.0 }, { 0.5, 1.0 } }
})
hl.curve("smoothOut", {
  type = "bezier",
  points = { { 0.05, 0.9 }, { 0.1, 1.05 } }
})
hl.curve("softSnap", {
  type = "bezier",
  points = { { 0.4, 0.0 }, { 0.2, 1.0 } }
})
hl.curve("fluent", {
  type = "bezier",
  points = { { 0.0, 0.0 }, { 0.2, 1.0 } }
})

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 3.0,
  curve = "fluent",
  style = "slide",
})
hl.animation({
  leaf = "windowsIn",
  enabled = true,
  speed = 3.0,
  curve = "fluent",
  style = "slide",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 3.0,
  curve = "fluent",
  style = "slide",
})
hl.animation({
  leaf = "windowsMove",
  enabled = true,
  speed = 3.0,
  curve = "overshot",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 3.0,
  curve = "smoothIn",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 3.0,
  curve = "smoothOut",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 3.0,
  curve = "smoothIn",
})
hl.animation({
  leaf = "fadeIn",
  enabled = true,
  speed = 3.0,
  curve = "smoothIn",
})
hl.animation({
  leaf = "fadeOut",
  enabled = true,
  speed = 3.0,
  curve = "smoothOut",
})
hl.animation({
  leaf = "fadeSwitch",
  enabled = true,
  speed = 3.0,
  curve = "smoothIn",
})
hl.animation({
  leaf = "fadeShadow",
  enabled = true,
  speed = 3.0,
  curve = "smoothIn",
})
hl.animation({
  leaf = "fadeDim",
  enabled = true,
  speed = 3.0,
  curve = "smoothIn",
})
hl.animation({
  leaf = "fadeDpms",
  enabled = true,
  speed = 3.0,
  curve = "smoothIn",
})
hl.animation({
  leaf = "fadeLayers",
  enabled = true,
  speed = 3.0,
  curve = "softSnap",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 3.0,
  curve = "softSnap",
  style = "slidefadevert 50%",
})
hl.animation({
  leaf = "specialWorkspace",
  enabled = true,
  speed = 3.0,
  curve = "fluent",
  style = "slidefadevert 50%",
})
