# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Animations Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/0.45.0/Configuring/Animations/ 

animations {
    enabled = yes
    bezier = overshot, 0.13, 0.99, 0.29, 1.1
    animation = windowsIn, 1, 7, default, slide
    animation = windowsOut, 1, 7, default, slide
    animation = windowsMove, 1, 7, default, popin 80%
    animation = workspacesIn, 1, 7, default, slide
    animation = workspacesOut, 1, 7, default, slide
    animation = specialWorkspaceIn, 1, 7, default, slidefadevert 100%
    animation = specialWorkspaceOut, 1, 7, default, slidefadevert 100%
    # animation = hyprfocusIn, 1, 2, overshot
    # animation = hyprfocusOut, 1, 2, overshot
}
