# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/0.45.0/Configuring/Keywords/#executing #

# exec-once = hyprpm reload
exec-once = rivet
exec-once = swww-daemon
exec-once = waypaper --restore
# exec-once = bash -c "sleep 2 && waybar"
# exec-once = qs -c noctalia-shell
exec-once = swaync
exec-once = sunsetr
exec-once = hyprctl setcursor "Catppuccin Mocha Light" 32
# exec-once = bash -c "while [ -z '$WAYLAND_DISPLAY' ]; do sleep 0.1; done && rivet"
exec-once = RIVET_SILENT=1 /home/alef/.cargo/bin/rivet

# ## Slow app launch fix
#exec-once = systemctl --user import-environment &
#exec-once = hash dbus-update-activation-environment 2>/dev/null &
#exec-once = dbus-update-activation-environment --all &

# ## Idle configuration
#exec-once = $idlehandler
