-- hyprland.lua
-- Generated by hypr-migrate from: autostart.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       0 resolved
--   Config keys:     0 emitted
--   Monitors:        0
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   6
--   Gestures:        0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   1  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.config.defaults")  -- was: source = ~/.config/hypr/config/defaults.conf
require("~/.config/hypr/config/defaults")

hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("swaync")
    hl.exec_cmd("sunsetr")
    hl.exec_cmd("hyprctl setcursor "Catppuccin Mocha Light" 32")
    hl.exec_cmd("bash -c "sleep 1 && RIVET_SILENT=1 /home/alef/.cargo/bin/rivet"")
end)
