# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Decorations Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#decoration

decoration {
    active_opacity = 1
    inactive_opacity = 1
    # rounding = 8
    rounding = 0
    dim_inactive = true
    dim_strength = 0.0
    dim_special = 0.5

    # https://wiki.hyprland.org/0.45.0/Configuring/Variables/#blur
    blur {
        enabled = false
        xray = false
    }

    # https://wiki.hyprland.org/0.45.0/Configuring/Variables/#shadow
    shadow {
        enabled = false
    }

}
