-- hyprland.lua
-- Generated by hypr-migrate from: decorations.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       0 resolved
--   Config keys:     12 emitted
--   Monitors:        0
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   0
--   Gestures:        0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

hl.config({
  decoration = {
    active_opacity = 1,
    blur = {
      enabled = true,
      xray = false,
    },
    dim_inactive = false,
    dim_special = 0.2,
    dim_strength = 0.0,
    inactive_opacity = 1,
    rounding = 0,
    shadow = {
      color = "rgba(121212aa)",
      enabled = true,
      range = 16,
      render_power = 2,
    },
  },
})
