# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Decorations Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/0.45.0/Configuring/Variables/#decoration

decoration {
    active_opacity = 1
    inactive_opacity = 1
    # rounding = 8
    rounding = 8
    dim_inactive = true
    dim_strength = 0.0
    dim_special = 0.5

    # https://wiki.hyprland.org/0.45.0/Configuring/Variables/#blur
    blur {
        enabled = true
        xray = false
    }

    # https://wiki.hyprland.org/0.45.0/Configuring/Variables/#shadow
    shadow {
        enabled = true
        ignore_window = true
        range = 16
        render_power = 2
        # offset = 8 8
        color = rgba(121212aa)
    }

}
