-- hyprland.lua
-- Generated by hypr-migrate from: defaults.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       10 resolved
--   Config keys:     0 emitted
--   Monitors:        0
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   0
--   Gestures:        0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

local filemanager = "pcmanfm"
local applauncher = "pkill -x wofi >/dev/null 2>&1 || wofi -i --show drun"
local wmenu = "pkill -x wmenu-drun >/dev/null 2>&1 || wmenu-drun"
local emojipicker = "pkill -x wmenu-emoji >/dev/null 2>&1 || wmenu-emoji"
local wallswitcher = "pkill -x waypaper >/dev/null 2>&1 || waypaper"
local terminal = "kitty"
local idlehandler = "swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'"
local capturing = "hyprshot -m region -r - | swappy -f -"
local screencap = "hyprshot -m output -m eDP-1 -r - | swappy -f -"
local browser = "zen-browser"
