-- hyprland.lua
-- Generated by hypr-migrate from: environment.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       0 resolved
--   Config keys:     0 emitted
--   Monitors:        0
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   0
--   Gestures:        0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

hl.env("AQ_DRM_DEVICES", "/dev/dri/card1:/dev/dri/card0")
hl.env("HYPRCURSOR_THEME", "Catppuccin Mocha Light")
hl.env("HYPRCURSOR_SIZE", "32")
hl.env("XCURSOR_THEME", "Catppuccin Mocha Light")
hl.env("XCURSOR_SIZE", "32")
hl.env("QT_CURSOR_THEME", "Catppuccin Mocha Light")
hl.env("QT_CURSOR_SIZE", "32")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_SCALE_FACTOR", "1.1")
hl.env("QS_ICON_THEME="Papirus Dark"", "")
