-- hyprland.lua
-- Generated by hypr-migrate from: input.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       0 resolved
--   Config keys:     6 emitted
--   Monitors:        0
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   1
--   Gestures:        0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

hl.config({
  input = {
    float_switch_override_focus = 2,
    follow_mouse = 1,
    kb_layout = "us",
    kb_model = "pc102",
    numlock_by_default = true,
  },
  cursor = {
    no_warps = true,
  },
})

hl.on("hyprland.start", function()
  hl.exec_cmd("setxkbmap -model pc105 -layout us -option grp:shifts_toggle")
end)
