-- hyprland.lua
-- Generated by hypr-migrate from: keybinds.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       0 resolved
--   Config keys:     80 emitted
--   Monitors:        0
--   Keybinds:        4 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 2
--   Exec commands:   0
--   Gestures:        0
--   Warnings:        150  ← search MIGRATION_WARNING
--   Review needed:   1  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

-- MIGRATION_NOTE: 'source' maps to require(); verify the path resolves correctly in your module setup
-- MIGRATED: require("~..config.hypr.config.defaults")  -- was: source = ~/.config/hypr/config/defaults.conf
require("~/.config/hypr/config/defaults")

hl.config({
  binds = {
    allow_workspace_cycles = 1,
    movefocus_cycles_fullscreen = true,
    window_direction_monitor_fallback = true,
  },
  -- MIGRATION_WARNING: Conflicting value for .bindd: '$mainMod, RETURN, Call special workspace scratchpad, togglespecialworkspace, scratchpad' (line 120) vs '$mainMod, T, Opens your preferred terminal emulator ($terminal), exec, $terminal' (line 9)
  bindd = "$mainMod, RETURN, Call special workspace scratchpad, togglespecialworkspace, scratchpad",
  -- MIGRATION_WARNING: Conflicting value for .bindel: ', XF86MonBrightnessDown, exec, brightnessctl -d intel_backlight s 5%-' (line 46) vs ', XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5% && pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+(?=%)' | awk '{if($1>100) system("pactl set-sink-volume @DEFAULT_SINK@ 100%")}' && pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+(?=%)' | awk '{print $1}' | head -1 > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob' (line 35)
  bindel = ", XF86MonBrightnessDown, exec, brightnessctl -d intel_backlight s 5%-",
})

hl.workspace_rule({ workspace = "1" })
hl.workspace_rule({ workspace = "1" })

hl.bind("$mainMod + mouse_down", function()
  hl.exec_cmd(
  "hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 * 1.1}')")
end)
hl.bind("$mainMod + mouse_up", function()
  hl.exec_cmd(
  "hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 * 0.9}')")
end)
hl.bind("$mainMod + mouse:273", hl.dsp.resizewindow(), { mouse = true })
hl.bind("$mainMod + mouse:272", hl.dsp.movewindow(), { mouse = true })
