-- hyprland.lua
-- Generated by hypr-migrate from: monitor.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       0 resolved
--   Config keys:     1 emitted
--   Monitors:        1
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   0
--   Gestures:        0
--   Warnings:        0  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

hl.env("GDK_SCALE", "1.20")

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.monitor({ output = "eDP-1", mode = "2560x1600", refresh = 240, position = "0x0" })
