$wallpaper = /home/alef/Pictures/walls/wallhaven-yqj1ex.png
$background = rgb(14171A)
$foreground = rgb(F5D9CD)
$color0 = rgb(3F4245)
$color1 = rgb(3E505A)
$color2 = rgb(785D63)
$color3 = rgb(527F8C)
$color4 = rgb(B76C6E)
$color5 = rgb(4F95A2)
$color6 = rgb(E2916F)
$color7 = rgb(E8C0AF)
$color8 = rgb(A2867A)
$color9 = rgb(3E505A)
$color10 = rgb(785D63)
$color11 = rgb(527F8C)
$color12 = rgb(B76C6E)
$color13 = rgb(4F95A2)
$color14 = rgb(E2916F)
$color15 = rgb(E8C0AF)
