$wallpaper = /home/alef/Pictures/walls/wallhaven-rr5r81.png
$background = rgb(151214)
$foreground = rgb(F4E7B9)
$color0 = rgb(403C40)
$color1 = rgb(4E424D)
$color2 = rgb(876767)
$color3 = rgb(717883)
$color4 = rgb(A87250)
$color5 = rgb(828F9B)
$color6 = rgb(A78B28)
$color7 = rgb(E7D492)
$color8 = rgb(A19466)
$color9 = rgb(554553)
$color10 = rgb(A17575)
$color11 = rgb(778191)
$color12 = rgb(CC7944)
$color13 = rgb(ADBECE)
$color14 = rgb(DFB936)
$color15 = rgb(E7D492)
