$wallpaper = /home/alef/Pictures/walls/broken_glass1.png
$background = rgb(0E0C14)
$foreground = rgb(ECEBF9)
$color0 = rgb(393741)
$color1 = rgb(B05AC3)
$color2 = rgb(6281A2)
$color3 = rgb(268CAD)
$color4 = rgb(8884B0)
$color5 = rgb(4196A3)
$color6 = rgb(9795B2)
$color7 = rgb(DBDAEE)
$color8 = rgb(9A99A6)
$color9 = rgb(CC38ED)
$color10 = rgb(6090C2)
$color11 = rgb(33BBE7)
$color12 = rgb(B5B0EB)
$color13 = rgb(57C8D9)
$color14 = rgb(C9C7ED)
$color15 = rgb(DBDAEE)
