-- hyprland.lua
-- Generated by hypr-migrate from: windowrules.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       0 resolved
--   Config keys:     0 emitted
--   Monitors:        0
--   Keybinds:        0 total, 0 collapsed into loops
--   Window rules:    20 total, 17 merged
--   Workspace rules: 1
--   Exec commands:   0
--   Gestures:        0
--   Warnings:        18  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

hl.workspace_rule({ workspace = "special:scratchpad", gaps_in = 0, gaps_out = 0 })

-- PATTERN: MERGED with line 9
-- MIGRATION_WARNING: Window rule conflict for 'float on, size 960 480': 'match:class ^(org.pulseaudio.pavucontrol)' (line 8) vs 'match:class ^(qt-sudo)$' (line 20)
hl.window_rule({
    match = { class = "float on" },
    match:class = "^(org.pulseaudio.pavucontrol)",
    match:title = "^(Picture in picture)$",
    match:title = "^(Save File)$",
    match:class = "^(zen)$",
    match:title = "^(Open File)$",
    match:title = "^(Blender File View)$",
    match:title = "^(Blender Render)$",
    match:class = "^(blueman-manager)$",
    match:class = "^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$",
    match:class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$",
    match:title = "^(Steam - Self Updater)$",
    match:class = "^(waypaper)$",
    match:class = "^(qt-sudo)$",
    match:class = "^(swayimg)$",
    match:class = "(clipse)",
    match:title = "^(Picture-in-Picture)$",
    match:title = "^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$",
    match:title = "^(.* — Prism Launcher 9.4)",
})
hl.window_rule({ match = { class = "pin on" }, match:title = "^(danmufloat)$" })
hl.window_rule({ match = { class = "no_blur on" }, match:class = "^(org.mozilla.firefox)$" })

hl.layer_rule({ match = { namespace = "animation slide top" }, match:namespace logout_dialog = true })
hl.layer_rule({ match = { namespace = "animation slide down" }, match:namespace waybar = true })
hl.layer_rule({ match = { namespace = "animation fade 50%" }, match:namespace wallpaper = true })
