# backend = "full"
# backend = "resized"
# backend = "fastresize"
backend = "wal"
# backend = "thumb"
# backend = "kmeans"

# color_space = "lab" # idc about this one..
# color_space = "labmixed" # idc about this one..
color_space = "lch" # idc about this one..
# color_space = "lchmixed" # idc about this one..
# color_space = "lchansi" # idc about this one..

palette = "dark16"
check_contrast = true
# threshold = 11
# saturation = 11

[templates]
mako = { src = "mako-colors", dst = "~/.cache/wallust/mako-colors" }
hyprland = { src = "hyprland.lua", dst = "~/.config/hypr/config/wallust-colors.lua" }
vscode = { src = 'vscode.json', dst = '~/.cache/wallust/colors.json' }
vscode2 = { src = 'vscode', dst = '~/.cache/wallust/colors' }
neopywal = { src = 'colors_neopywal.vim', dst = '~/.cache/wallust/colors_neopywal.vim' }
wlogout = { src = 'waybar-colors.css', dst = '~/.config/wlogout/colors.css' }
wmenu = { src = 'wmenu-colors', dst = '~/.config/wmenu/colors' }
pywalzen = { src = 'vscode.json', dst = '~/.cache/wal/colors.json' }
kitty = { src = 'kitty-colors.conf', dst = '~/.config/kitty/colors.conf' }

