# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E2FFFD
background         #0E0E0E
cursor             #BBB7AB

active_tab_foreground     #0E0E0E
active_tab_background     #E2FFFD
inactive_tab_foreground   #E2FFFD
inactive_tab_background   #0E0E0E

active_border_color   #E2FFFD
inactive_border_color #0E0E0E
bell_border_color     #A16790

color0      #393939
color1		#A16790
color2		#907A6E
color3		#707C85
color4		#93916A
color5		#BBA6B9
color6		#81BFBA
color7		#CDF7F3
color8		#8FADAA
color9		#B95F9F
color10		#9A7662
color11		#95A5B1
color12		#C4C18D
color13		#FADDF7
color14		#ACFFF8
color15		#CDF7F3
