# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4E7B9
background         #151214
cursor             #BC9A83

active_tab_foreground     #151214
active_tab_background     #F4E7B9
inactive_tab_foreground   #F4E7B9
inactive_tab_background   #151214

active_border_color   #F4E7B9
inactive_border_color #151214
bell_border_color     #4E424D

color0      #403C40
color1		#4E424D
color2		#876767
color3		#717883
color4		#A87250
color5		#828F9B
color6		#A78B28
color7		#E7D492
color8		#A19466
color9		#554553
color10		#A17575
color11		#778191
color12		#CC7944
color13		#ADBECE
color14		#DFB936
color15		#E7D492
