# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #CFE4C9
background         #0F0F14
cursor             #908A9A

active_tab_foreground     #0F0F14
active_tab_background     #CFE4C9
inactive_tab_foreground   #CFE4C9
inactive_tab_background   #0F0F14

active_border_color   #CFE4C9
inactive_border_color #0F0F14
bell_border_color     #3F4453

color0      #3A3A40
color1		#3F4453
color2		#695578
color3		#486990
color4		#9F70AB
color5		#278AAA
color6		#608C55
color7		#B2D1AA
color8		#7D9277
color9		#41475C
color10		#785E8C
color11		#4D79AC
color12		#AE5DC3
color13		#15A6D7
color14		#76B366
color15		#B2D1AA
